version: '3'

services:
    web:
        image: rubikvn/rubikvn:latest
        build: .
        container_name: rubikvn_web
        ports:
            - "3000:3000"
        expose:
            - "80"
            - "443"
            - "8080"
        stdin_open: true
        tty: true
